name: Build Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          libssl-dev \
          python3
        
    - name: Configure
      run: |
        ./configure
        
    - name: Build
      run: |
        python3 x.py build --stage 1

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: rust-build
        path: |
          build/x86_64-pc-windows-msvc/stage1/
          build/x86_64-pc-windows-msvc/stage0-tools-bin/
        retention-days: 1
