name: Build Rust Compiler (Windows GNU x86-64)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TARGET: x86_64-pc-windows-gnu
  HOST: x86_64-pc-windows-gnu
  RUST_BOOTSTRAP: 1

jobs:
  build:
    name: Build Rust Compiler
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install required tools
      run: |
        choco install -y python --version 3.10.0
        choco install -y cmake
        choco install -y ninja
        choco install -y mingw --version 8.1.0
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv

    - name: Set up environment
      run: |
        echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

    - name: Build Rust
      run: |
        python .\x.py build --stage 2 --target=$env:TARGET --host=$env:TARGET
        python .\x.py dist --stage 2 --target=$env:TARGET --host=$env:TARGET

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: rustc-${{ env.TARGET }}
        path: |
          build/dist/*.tar.gz
          build/dist/*.tar.xz
