name: Windows GNU Build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build Rust Compiler
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install required tools
      run: |
        choco install -y python3
        python -m pip install --upgrade pip
        pip install ninja
        refreshenv

    - name: Set up MSYS2
      run: |
        choco install -y msys2 --params="/NoUpdate"
        refreshenv
        C:\msys64\usr\bin\bash -lc "pacman --noconfirm -Syu"
        C:\msys64\usr\bin\bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain make cmake"

    - name: Configure
      shell: C:\msys64\usr\bin\bash.exe -l {0}
      run: |
        ./configure \
          --target=$TARGET \
          --enable-extended \
          --tools=rust-analyzer

    - name: Build
      shell: C:\msys64\usr\bin\bash.exe -l {0}
      run: |
        make -j$(nproc)

    - name: Package artifacts
      shell: C:\msys64\usr\bin\bash.exe -l {0}
      run: |
        make dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rustc-${{ env.TARGET }}
        path: ${{ github.workspace }}/build/dist/*.tar.xz
