name: Windows Rust Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build Rust
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: latest
        sdk: latest

    - name: Install prerequisites
      shell: pwsh
      run: |
        choco install -y cmake ninja
        refreshenv

    - name: Create config.toml
      shell: cmd
      run: |
        echo [llvm] > config.toml
        echo download-ci-llvm = true >> config.toml
        echo. >> config.toml
        echo [build] >> config.toml
        echo extended = true >> config.toml
        echo. >> config.toml
        echo [target.x86_64-pc-windows-msvc] >> config.toml
        echo default-linker = "lld-link" >> config.toml

    - name: Build Rust (Stage 1)
      shell: cmd
      run: |
        python x.py build --stage 1 library/std

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rust-build
        path: |
          build\x86_64-pc-windows-msvc\stage1\
          build\x86_64-pc-windows-msvc\stage0-tools-bin\
