name: Build Rust Compiler (Windows GNU x86-64)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  TARGET: x86_64-pc-windows-gnu
  HOST: x86_64-pc-windows-gnu
  RUST_BACKTRACE: 1
  MSYS2_PATH: C:\msys64\usr\bin

jobs:
  build:
    name: Build Rust Compiler
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install required tools
      run: |
        choco install -y python3
        python -m pip install --upgrade pip
        pip install ninja
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv

    - name: Set up MSYS2
      run: |
        choco install -y msys2 --params="/NoUpdate"
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv
        $env:Path += ";$env:MSYS2_PATH"
        bash -lc "pacman --noconfirm -Syu"
        bash -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain make cmake"

    - name: Configure
      run: |
        bash -lc "./configure \
          --target=$env:TARGET \
          --host=$env:HOST \
          --enable-extended \
          --tools=rust-analyzer
          --set rust.channel=nightly"

    - name: Build
      run: |
        bash -lc "make -j$(nproc)"

    - name: Package artifacts
      run: |
        bash -lc "make dist"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rustc-${{ env.TARGET }}
        path: ${{ github.workspace }}/build/dist/*.tar.xz
